# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dox.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(838, 574)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.webView_Main_Map = QtWebKitWidgets.QWebView(self.centralwidget)
        self.webView_Main_Map.setUrl(QtCore.QUrl("about:blank"))
        self.webView_Main_Map.setObjectName("webView_Main_Map")
        self.gridLayout.addWidget(self.webView_Main_Map, 0, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 8, 4, 3, 2)
        self.gridLayout_9 = QtWidgets.QGridLayout()
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.textBrowser_MainDescription = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_MainDescription.setObjectName("textBrowser_MainDescription")
        self.gridLayout_9.addWidget(self.textBrowser_MainDescription, 0, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(0, 120, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_9.addItem(spacerItem, 0, 2, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_9, 7, 4, 1, 2)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.news = QtWebKitWidgets.QWebView(self.centralwidget)
        self.news.setUrl(QtCore.QUrl("about:blank"))
        self.news.setObjectName("news")
        self.gridLayout_4.addWidget(self.news, 0, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_4, 4, 2, 7, 2)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 14, 0, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.graphicsView_Main_Pic = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView_Main_Pic.setObjectName("graphicsView_Main_Pic")
        self.gridLayout_3.addWidget(self.graphicsView_Main_Pic, 2, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_3, 4, 5, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(150, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 5, 4, 1, 2)
        self.gridLayout_12 = QtWidgets.QGridLayout()
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.gridLayout_12.addWidget(self.textBrowser_2, 0, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_12, 4, 4, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_Previous = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Previous.setObjectName("pushButton_Previous")
        self.horizontalLayout.addWidget(self.pushButton_Previous)
        self.pushButton_Next = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Next.setObjectName("pushButton_Next")
        self.horizontalLayout.addWidget(self.pushButton_Next)
        self.gridLayout_2.addLayout(self.horizontalLayout, 6, 4, 1, 2)
        spacerItem2 = QtWidgets.QSpacerItem(125, 0, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 3, 5, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem3, 12, 2, 1, 1)
        self.command_line = QtWidgets.QLineEdit(self.centralwidget)
        self.command_line.setObjectName("command_line")
        self.gridLayout_2.addWidget(self.command_line, 14, 2, 1, 4)
        spacerItem4 = QtWidgets.QSpacerItem(40, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem4, 12, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(150, 0, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem5, 3, 4, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(0, 140, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_2.addItem(spacerItem6, 4, 6, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout.addWidget(self.lineEdit)
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.textBrowser.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout.addWidget(self.textBrowser)
        self.gridLayout_2.addLayout(self.verticalLayout, 4, 0, 7, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 838, 27))
        self.menubar.setObjectName("menubar")
        self.menuAadf = QtWidgets.QMenu(self.menubar)
        self.menuAadf.setObjectName("menuAadf")
        self.menuAdd_Person = QtWidgets.QMenu(self.menubar)
        self.menuAdd_Person.setObjectName("menuAdd_Person")
        self.menuSearch = QtWidgets.QMenu(self.menubar)
        self.menuSearch.setObjectName("menuSearch")
        self.menuDatabase = QtWidgets.QMenu(self.menubar)
        self.menuDatabase.setObjectName("menuDatabase")
        self.menuBlockchain = QtWidgets.QMenu(self.menubar)
        self.menuBlockchain.setObjectName("menuBlockchain")
        self.menuSettings = QtWidgets.QMenu(self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        MainWindow.setMenuBar(self.menubar)
        self.actionPerson = QtWidgets.QAction(MainWindow)
        self.actionPerson.setObjectName("actionPerson")
        self.actionCrime = QtWidgets.QAction(MainWindow)
        self.actionCrime.setObjectName("actionCrime")
        self.actionEvent = QtWidgets.QAction(MainWindow)
        self.actionEvent.setObjectName("actionEvent")
        self.actionEvent_2 = QtWidgets.QAction(MainWindow)
        self.actionEvent_2.setObjectName("actionEvent_2")
        self.actionCreate_Relationship = QtWidgets.QAction(MainWindow)
        self.actionCreate_Relationship.setObjectName("actionCreate_Relationship")
        self.actionImport = QtWidgets.QAction(MainWindow)
        self.actionImport.setObjectName("actionImport")
        self.actionImport_From_Blockchain = QtWidgets.QAction(MainWindow)
        self.actionImport_From_Blockchain.setObjectName("actionImport_From_Blockchain")
        self.actionExport = QtWidgets.QAction(MainWindow)
        self.actionExport.setObjectName("actionExport")
        self.actionExport_To_Blockchain = QtWidgets.QAction(MainWindow)
        self.actionExport_To_Blockchain.setObjectName("actionExport_To_Blockchain")
        self.actionSettings = QtWidgets.QAction(MainWindow)
        self.actionSettings.setObjectName("actionSettings")
        self.actionSelected = QtWidgets.QAction(MainWindow)
        self.actionSelected.setObjectName("actionSelected")
        self.actionConnect = QtWidgets.QAction(MainWindow)
        self.actionConnect.setObjectName("actionConnect")
        self.actionMine = QtWidgets.QAction(MainWindow)
        self.actionMine.setObjectName("actionMine")
        self.actionFind_Nodes = QtWidgets.QAction(MainWindow)
        self.actionFind_Nodes.setObjectName("actionFind_Nodes")
        self.actionSettings_2 = QtWidgets.QAction(MainWindow)
        self.actionSettings_2.setObjectName("actionSettings_2")
        self.menuAadf.addSeparator()
        self.menuAdd_Person.addSeparator()
        self.menuAdd_Person.addAction(self.actionPerson)
        self.menuAdd_Person.addAction(self.actionCrime)
        self.menuAdd_Person.addAction(self.actionEvent)
        self.menuAdd_Person.addAction(self.actionEvent_2)
        self.menuDatabase.addAction(self.actionImport)
        self.menuDatabase.addAction(self.actionImport_From_Blockchain)
        self.menuDatabase.addAction(self.actionExport)
        self.menuDatabase.addAction(self.actionExport_To_Blockchain)
        self.menuDatabase.addAction(self.actionSettings)
        self.menuBlockchain.addAction(self.actionConnect)
        self.menuBlockchain.addAction(self.actionMine)
        self.menuBlockchain.addAction(self.actionFind_Nodes)
        self.menuBlockchain.addAction(self.actionSettings_2)
        self.menubar.addAction(self.menuAadf.menuAction())
        self.menubar.addAction(self.menuAdd_Person.menuAction())
        self.menubar.addAction(self.menuSearch.menuAction())
        self.menubar.addAction(self.menuDatabase.menuAction())
        self.menubar.addAction(self.menuBlockchain.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Command Line:"))
        self.pushButton_Previous.setText(_translate("MainWindow", "Previous"))
        self.pushButton_Next.setText(_translate("MainWindow", "Next"))
        self.menuAadf.setTitle(_translate("MainWindow", "Home"))
        self.menuAdd_Person.setTitle(_translate("MainWindow", "Add"))
        self.menuSearch.setTitle(_translate("MainWindow", "Search"))
        self.menuDatabase.setTitle(_translate("MainWindow", "Database"))
        self.menuBlockchain.setTitle(_translate("MainWindow", "Blockchain"))
        self.menuSettings.setTitle(_translate("MainWindow", "Settings"))
        self.actionPerson.setText(_translate("MainWindow", "Person"))
        self.actionCrime.setText(_translate("MainWindow", "Group"))
        self.actionEvent.setText(_translate("MainWindow", "Crime"))
        self.actionEvent_2.setText(_translate("MainWindow", "Event"))
        self.actionCreate_Relationship.setText(_translate("MainWindow", "Create Relationship"))
        self.actionImport.setText(_translate("MainWindow", "Import"))
        self.actionImport_From_Blockchain.setText(_translate("MainWindow", "Import From Blockchain"))
        self.actionExport.setText(_translate("MainWindow", "Export"))
        self.actionExport_To_Blockchain.setText(_translate("MainWindow", "Export To Blockchain"))
        self.actionSettings.setText(_translate("MainWindow", "Settings"))
        self.actionSelected.setText(_translate("MainWindow", "Selected"))
        self.actionConnect.setText(_translate("MainWindow", "Connect"))
        self.actionMine.setText(_translate("MainWindow", "Mine"))
        self.actionFind_Nodes.setText(_translate("MainWindow", "Find Nodes"))
        self.actionSettings_2.setText(_translate("MainWindow", "Settings"))

from PyQt5 import QtWebKitWidgets
