# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(336, 303)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tableView = QtWidgets.QTableView(self.centralwidget)
        self.tableView.setObjectName("tableView")
        self.gridLayout.addWidget(self.tableView, 0, 0, 1, 1)
        self.search_text = QtWidgets.QLineEdit(self.centralwidget)
        self.search_text.setText("")
        self.search_text.setObjectName("search_text")
        self.gridLayout.addWidget(self.search_text, 1, 0, 1, 1)
        self.search = QtWidgets.QPushButton(self.centralwidget)
        self.search.setObjectName("search")
        self.gridLayout.addWidget(self.search, 2, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 336, 27))
        self.menuBar.setObjectName("menuBar")
        self.menuNew_Case = QtWidgets.QMenu(self.menuBar)
        self.menuNew_Case.setObjectName("menuNew_Case")
        self.menuDelete = QtWidgets.QMenu(self.menuBar)
        self.menuDelete.setObjectName("menuDelete")
        self.menuSettings = QtWidgets.QMenu(self.menuBar)
        self.menuSettings.setObjectName("menuSettings")
        self.menuMap = QtWidgets.QMenu(self.menuBar)
        self.menuMap.setObjectName("menuMap")
        MainWindow.setMenuBar(self.menuBar)
        self.actionNearby = QtWidgets.QAction(MainWindow)
        self.actionNearby.setObjectName("actionNearby")
        self.actionSearch_Address = QtWidgets.QAction(MainWindow)
        self.actionSearch_Address.setObjectName("actionSearch_Address")
        self.actionSelected = QtWidgets.QAction(MainWindow)
        self.actionSelected.setObjectName("actionSelected")
        self.actionDelete = QtWidgets.QAction(MainWindow)
        self.actionDelete.setObjectName("actionDelete")
        self.actionSaveChanges = QtWidgets.QAction(MainWindow)
        self.actionSaveChanges.setObjectName("actionSaveChanges")
        self.actionNew_Individual = QtWidgets.QAction(MainWindow)
        self.actionNew_Individual.setObjectName("actionNew_Individual")
        self.actionNew_Group = QtWidgets.QAction(MainWindow)
        self.actionNew_Group.setObjectName("actionNew_Group")
        self.actionNew_Event = QtWidgets.QAction(MainWindow)
        self.actionNew_Event.setObjectName("actionNew_Event")
        self.actionNew_Person = QtWidgets.QAction(MainWindow)
        self.actionNew_Person.setObjectName("actionNew_Person")
        self.action_New_Group = QtWidgets.QAction(MainWindow)
        self.action_New_Group.setObjectName("action_New_Group")
        self.actionProxy_Settings = QtWidgets.QAction(MainWindow)
        self.actionProxy_Settings.setObjectName("actionProxy_Settings")
        self.actionDatabase_Settings = QtWidgets.QAction(MainWindow)
        self.actionDatabase_Settings.setObjectName("actionDatabase_Settings")
        self.actionBlockchain_Settings = QtWidgets.QAction(MainWindow)
        self.actionBlockchain_Settings.setObjectName("actionBlockchain_Settings")
        self.menuNew_Case.addAction(self.actionNew_Event)
        self.menuNew_Case.addAction(self.actionNew_Person)
        self.menuNew_Case.addAction(self.action_New_Group)
        self.menuDelete.addAction(self.actionDelete)
        self.menuDelete.addAction(self.actionSaveChanges)
        self.menuSettings.addAction(self.actionProxy_Settings)
        self.menuSettings.addAction(self.actionDatabase_Settings)
        self.menuSettings.addAction(self.actionBlockchain_Settings)
        self.menuMap.addAction(self.actionNearby)
        self.menuMap.addAction(self.actionSearch_Address)
        self.menuMap.addAction(self.actionSelected)
        self.menuBar.addAction(self.menuNew_Case.menuAction())
        self.menuBar.addAction(self.menuDelete.menuAction())
        self.menuBar.addAction(self.menuSettings.menuAction())
        self.menuBar.addAction(self.menuMap.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.search_text.setPlaceholderText(_translate("MainWindow", "Search... e.g. \"John Smith\""))
        self.search.setText(_translate("MainWindow", "Search"))
        self.menuNew_Case.setTitle(_translate("MainWindow", "New Case"))
        self.menuDelete.setTitle(_translate("MainWindow", "Edit"))
        self.menuSettings.setTitle(_translate("MainWindow", "Settings"))
        self.menuMap.setTitle(_translate("MainWindow", "Map"))
        self.actionNearby.setText(_translate("MainWindow", "Nearby"))
        self.actionSearch_Address.setText(_translate("MainWindow", "Search Address"))
        self.actionSelected.setText(_translate("MainWindow", "Selected"))
        self.actionDelete.setText(_translate("MainWindow", "Delete"))
        self.actionSaveChanges.setText(_translate("MainWindow", "SaveChanges"))
        self.actionNew_Individual.setText(_translate("MainWindow", "New Individual"))
        self.actionNew_Group.setText(_translate("MainWindow", "New Individual"))
        self.actionNew_Event.setText(_translate("MainWindow", "New Event"))
        self.actionNew_Person.setText(_translate("MainWindow", "New Person"))
        self.action_New_Group.setText(_translate("MainWindow", " New Group"))
        self.actionProxy_Settings.setText(_translate("MainWindow", "Proxy"))
        self.actionDatabase_Settings.setText(_translate("MainWindow", "Database"))
        self.actionBlockchain_Settings.setText(_translate("MainWindow", "Blockchain"))

